//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphDownloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphDownloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Application Error has occurred.
        /// </summary>
        internal static string appError {
            get {
                return ResourceManager.GetString("appError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while connecting to the server. Check your connection and settings and try again..
        /// </summary>
        internal static string dlError {
            get {
                return ResourceManager.GetString("dlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate .NET Framework 4. Please ensure you have version 4 or greater installed and try again..
        /// </summary>
        internal static string fwError {
            get {
                return ResourceManager.GetString("fwError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Please check your hosts file and try again&quot;..
        /// </summary>
        internal static string hostFileError {
            get {
                return ResourceManager.GetString("hostFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download graphs.
        /// </summary>
        internal static string settingsError {
            get {
                return ResourceManager.GetString("settingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your chosen dates. Click the calendar icons to choose a start and end date and try again..
        /// </summary>
        internal static string settingsErrorDate {
            get {
                return ResourceManager.GetString("settingsErrorDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the folder path. Click Browse... to choose what folder graphs will be saved to..
        /// </summary>
        internal static string settingsErrorFolder {
            get {
                return ResourceManager.GetString("settingsErrorFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your selected host group. Make sure you have chosen a valid group or loaded a valid file. See the documentation for more information..
        /// </summary>
        internal static string settingsErrorHosts {
            get {
                return ResourceManager.GetString("settingsErrorHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your settings and try again.
        /// </summary>
        internal static string settingsErrorText {
            get {
                return ResourceManager.GetString("settingsErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Error.
        /// </summary>
        internal static string settingsErrorTitle {
            get {
                return ResourceManager.GetString("settingsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application encountered an unknown error. Check your settings and try again..
        /// </summary>
        internal static string unknownError {
            get {
                return ResourceManager.GetString("unknownError", resourceCulture);
            }
        }
    }
}
